
source('~/Fellowship/projects/hc/fCOuNT/fCOuNT.R')
source('~/Fellowship/projects/hc/fCOuNT/fCOuNT_MAIN.R')
source('~/Fellowship/projects/hc/fCOuNT/fCOuNT_GEN_PLOT_OPTIONS.R')
source('~/Fellowship/projects/hc/fCOuNT/fCOuNT_GEN_HC_OPTIONS.R')
source('~/Fellowship/projects/hc/fCOuNT/fCOuNT_RETRIEVE_FC_MATRICES.R')
source('~/Fellowship/projects/hc/fCOuNT/fCOuNT_RUN_1ST_LEVEL_TESTS.R')
source('~/Fellowship/projects/hc/fCOuNT/fCOuNT_RUN_2ND_LEVEL_TESTS.R')
source('~/Fellowship/projects/hc/fCOuNT/fCOuNT_CALC_HC_P_VALUE.R')
source('~/Fellowship/projects/hc/fCOuNT/fCOuNT_HIGHER_CRITICISM.R')
source('~/Fellowship/projects/hc/fCOuNT/fCOuNT_PLOT_RESULTS.R')
source('~/Fellowship/projects/hc/fCOuNT/run_1st_level_tests.R')
